/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package paula.prueba.automation;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
