/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package paula.prueba.automation;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.io.File;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       /* Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());*/
    	File file = new File("D:\\PaulaVallejo\\driver\\chromedriver.exe");
    	System.setProperty("webdriver.chrome.driver", file.getAbsolutePath());
    	WebDriver driver = new ChromeDriver();
    	driver.get("https://www.ebay.com/");
    	driver.close();
    	driver.quit();
    }
}
